<?php

namespace NYPL\Services\Test\Controller;

use NYPL\Services\Controller\JobController;
use PHPUnit\Framework\TestCase;
use Slim\Http\Response;

class JobControllerTest extends TestCase
{
    public $fakeJobController;

    public function setUp()
    {
        parent::setUp();

        $this->fakeJobController = new class extends JobController
        {
            public function __construct()
            {
            }

            public function createJob()
            {
                $response = new Response();
                $stubReponse = preg_replace(
                    '/\s/',
                    '',
                    file_get_contents(__DIR__ . '/../Stubs/job-create-response.json')
                );
                $response->getBody()->write($stubReponse);

                return $response;
            }

            public function getJob($id)
            {
                $response = new Response();
                $stubResponse = preg_replace(
                  '/\s/',
                  '',
                  file_get_contents(__DIR__ . '/../Stubs/job-get-response.json')
                );
                $response->getBody()->write($stubResponse);

                return $response;
            }

            public function createJobNotice($id)
            {
                return parent::createJobNotice($id); // TODO: Change the autogenerated stub
            }

            public function startJob($id)
            {
                return parent::startJob($id); // TODO: Change the autogenerated stub
            }

            public function setJobSuccess($id)
            {
                return parent::setJobSuccess($id); // TODO: Change the autogenerated stub
            }

            public function setJobFailure($id)
            {
                return parent::setJobFailure($id); // TODO: Change the autogenerated stub
            }

        };
    }

    /**
     * @covers \NYPL\Services\Controller\JobController::createJob
     */
    public function testCreationOfJob()
    {
        $controller = $this->fakeJobController;

        $response = $controller->createJob();

        $requestData = '{
              "data":
              {
                "id": "1559e793b78b2a0",
                "started": false,
                "finished": false,
                "success": false,
                "notices": null,
                "successRedirectUrl": "",
                "startCallbackUrl": "",
                "successCallbackUrl": "",
                "failureCallbackUrl": "",
                "updateCallbackUrl": ""
              }
            }';

        $createResponse = preg_replace('/\s/', '', $requestData);

        $body = $response->getBody();
        self::assertTrue($response->getStatusCode() == 200);
        self::assertSame($createResponse, $body->__toString());
    }

    public function testGetHoldRequest()
    {
        $controller = $this->fakeJobController;

        $response = $controller->getJob("1559e793b78b2a0");

        $responseData = '{
          "data": {
            "id": "1559e793b78b2a0",
            "started": false,
            "finished": false,
            "success": false,
            "notices": null,
            "successRedirectUrl": "",
            "startCallbackUrl": "",
            "successCallbackUrl": "",
            "failureCallbackUrl": "",
            "updateCallbackUrl": ""
          }
        }';

        $jobResponse = preg_replace('/\s/', '', $responseData);

        $body = $response->getBody();
        self::assertTrue($response->getStatusCode() == 200);
        self::assertSame($jobResponse, $body->__toString());
    }
}
